<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://www.smartcity.com/air/qualiteair"
           targetNamespace="http://www.smartcity.com/air/qualiteair"
           elementFormDefault="qualified">

    <xs:element name="GetAQIRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zone" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetAQIResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aqi" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>