spring.application.name=service-orchestrateur

server.port=5005

app.url.mobilite=http://localhost:5001
app.url.qualiteair=http://localhost:5002/ws
app.url.evenements=http://localhost:5004/graphql
app.url.urgences.host=${APP_URL_URGENCES_HOST:service-urgences}
app.url.urgences.port=${APP_URL_URGENCES_PORT:50051}